Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,19 +13,27 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.9'  # Specify your Python version
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.9'  # Specify your Python version
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install detect-secrets
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install detect-secrets
 
-    - name: Run detect-secrets
-      run: |
-        detect-secrets audit .secrets.baseline --all
+      - name: Run detect-secrets
+        id: scan
+        run: |
+          detect-secrets scan --baseline .secrets.baseline
+          
+          # Check the exit code and handle failure
+          if [ $? -ne 0 ]; then
+            echo "Secrets detected! Failing the job."
+            exit 1
+          fi
+
